### ISSUE TITLE
Non-normal context does not activate non-normal commands.

### ISSUE THREAD

**Issue by Kelerchian** [LipSurf/plugins#24]
Using PluginBase.util.enterContext to enter a context does not show the commands in the help menu.

For example this plugin has one command which is non-normal and only active in context "somecontext". It the beginning, context is switched to `["somecontext"]` without `Normal` context. This renders the command not showing in the command list in the help

```
PluginBase.util.enterContext(["somecontext"]);

export default <IPluginBase & IPlugin>{
  ...PluginBase,
  ...{
    niceName: "SomePlugin",
    description: 'A "SomePlugin" plugin that works on the example.com domain.',
    match: /.*\.example.com/,
    version: "1.0.0",
    commands: [
      {
        name: "Some::Non-normal",
        match: "hello example",
        context: "somecontext",
        normal: false,
        pageFn: () => {
          console.log("hello example");
        }
      }
    ]
  }
};
```

![help-widget-non-normal](https://user-images.githubusercontent.com/11693412/95227745-ada64080-0828-11eb-8fab-6443def9b65c.PNG)

**Comment by Kelerchian** [comment]
I figured here might be not the proper place for lipsurf issues. Feel free to close this issue if this is not the proper place.
I've copied it [here](https://discuss.lipsurf.com/t/non-normal-context-does-not-activate-non-normal-commands/293).

**Comment by mikob** [comment]
Responded on the forums
