### ISSUE TITLE
Incorrect regexp in match

### ISSUE THREAD

**Issue by aparajita** [LipSurf/plugins#4]
In all of the plugin sources you are using regexps like this for the `match` URL:

```js
/^https?:\/\/news.ycombinator.com/
```

The dots in the URL should be escaped:

```js
/^https?:\/\/news\.ycombinator\.com/
```

Currently the regexp above would match something like `https://news_ycombinator_com`, which is clearly not what you intended.

**Comment by mikob** [comment]
Thanks, yep, that needs to be fixed!

**Comment by mikob** [comment]
Fixed in https://github.com/LipSurf/plugins/commit/c1a2518e728338b538ec72090952a1d598e32b53
