### ISSUE TITLE
Change compile task to compile only changed files

### ISSUE THREAD

**Issue by aparajita** [LipSurf/plugins#6]
Currently, the compile task in the gulpfile compiles **every** plugin, even if only one has changed. This results in **very** long compile times already, which will only get worse as more plugins are added.

The problem is you're using `glob.sync` and passing the result of that `gulp.src`. This is unnecessary, `gulp.src` uses `glob` under the hood, so you can exclude `@types` directly within `gulp.src`.

See https://gulpjs.org/API.html#gulp-src-globs-options for reference.

**Comment by mikob** [comment]
Fixed in https://github.com/LipSurf/plugins/releases/tag/v1.5.0
Also switched the build tool over to rollup. Compilation finishes in milliseconds now.

**Comment by aparajita** [comment]
Yes, Rollup is much better for this kind of project.

**Comment by mikob** [comment]
@aparajita FYI there were some slight changes to the format of the Plugins. I haven't documented them yet but they're pretty simple. I've updated your plugins in this repo accordingly (es6 module instead of namespace is the most visible difference)
